import cv2
import time
import shutil
import sys
import signal
import os; os.environ["PYGAME_HIDE_SUPPORT_PROMPT"] = "1"
import pygame
import typer
import subprocess
import tempfile

app = typer.Typer()

DEFAULT_ASCII_CHARS = " ░▒▓█"

playback_stopped = False
temporary_audio_path = None

def handle_sigint(signal_number, stack_frame):
    """
    Handles the SIGINT signal (usually generated by Ctrl+C) to safely stop the video playback.

    This function sets a global stop flag which the main loop checks to terminate the
    program gracefully, ensuring resources like audio are cleaned up.
    """
    global playback_stopped
    playback_stopped = True

signal.signal(signal.SIGINT, handle_sigint)

def frame_to_ascii(video_frame, target_width, ascii_chars):
    """
    Converts a single video frame (image) into an ASCII art string representation.

    It resizes the frame to the specified width, converts it to grayscale, and maps
    pixel brightness to characters from the provided character set.

    :param video_frame: The image frame from the video.
    :param target_width: The target width in characters for the ASCII output.
    :param ascii_chars: A string of characters to map pixel intensity to.
    :return: A string representing the frame in ASCII art.
    """
    target_height = int(video_frame.shape[0] * (target_width / video_frame.shape[1]) * 0.5)
    resized_frame = cv2.resize(video_frame, (target_width, target_height))
    grayscale_frame = cv2.cvtColor(resized_frame, cv2.COLOR_BGR2GRAY)
    ascii_rows = []
    charset_length = len(ascii_chars)
    for pixel_row in grayscale_frame:
        ascii_row_chars = []
        for pixel_brightness in pixel_row:
            char_index = int(pixel_brightness) * charset_length // 256
            ascii_char = ascii_chars[char_index]
            ascii_row_chars.append(ascii_char if ascii_char != ascii_chars[0] else " ")
        ascii_rows.append("".join(ascii_row_chars))
    return "\n".join(ascii_rows)

def move_cursor():
    """
    Moves the terminal cursor to the top-left corner (home position).

    This allows the next frame to overwrite the current one without clearing the screen,
    which reduces flickering during playback.
    """
    sys.stdout.write("\033[H")
    sys.stdout.flush()

def clear_screen():
    """
    Clears the entire terminal screen.

    This is used before playback starts and after it ends to ensure a clean display area.
    """
    sys.stdout.write("\033[2J")
    sys.stdout.flush()

def extract_audio(ffmpeg_executable, source_video_path, playback_speed):
    """
    Extracts the audio track from the video file using FFmpeg.

    It adjusts the audio speed to match the video playback speed and saves the result
    as a temporary WAV file.

    :param ffmpeg_executable: The path to the FFmpeg executable.
    :param source_video_path: The path to the source video file.
    :param playback_speed: The playback speed factor.
    :return: The path to the temporary audio file.
    """
    file_descriptor, audio_output_path = tempfile.mkstemp(suffix=".wav")
    os.close(file_descriptor)

    audio_filters = []
    current_speed_factor = playback_speed
    while current_speed_factor > 2.0:
        audio_filters.append("atempo=2.0")
        current_speed_factor /= 2.0
    while current_speed_factor < 0.5:
        audio_filters.append("atempo=0.5")
        current_speed_factor *= 2.0
    audio_filters.append(f"atempo={current_speed_factor}")

    subprocess.run(
        [
            ffmpeg_executable,
            "-y",
            "-i", source_video_path,
            "-vn",
            "-filter:a", ",".join(audio_filters),
            "-acodec", "pcm_s16le",
            "-ar", "44100",
            "-ac", "2",
            audio_output_path,
        ],
        stdout=subprocess.DEVNULL,
        stderr=subprocess.DEVNULL,
        check=True,
    )
    return audio_output_path

def resolve_ffmpeg():
    """
    Locates the FFmpeg executable required for audio processing.

    It first checks for a 'bin' folder relative to this script, and then checks the
    system PATH. If FFmpeg is not found, the program exits with an error.

    :return: The path to the FFmpeg executable.
    """
    executable_name = "ffmpeg.exe" if sys.platform.startswith("win") else "ffmpeg"

    if getattr(sys, 'frozen', False):
        base_path = os.path.dirname(sys.executable)
    else:
        base_path = os.path.dirname(os.path.abspath(__file__))

    local_bin_path = os.path.join(base_path, "bin", executable_name)
    if os.path.isfile(local_bin_path):
        return local_bin_path

    system_bin_path = shutil.which("ffmpeg")
    if system_bin_path:
        return system_bin_path

    print("Error: FFmpeg not installed.")
    raise typer.Exit(1)

@app.command(epilog="Some terminals can 'zoom in and out' using Ctrl+Plus/Minus. Zooming out may improve quality at the cost of performance.")
def play(
    video: str = typer.Argument(..., help="The path to the video file you want to play."),
    scale: float = typer.Option(1.0, help="Scale factor for the video size relative to terminal width."),
    speed: float = typer.Option(1.0, help="Playback speed multiplier (e.g., 2.0 for 2x speed)."),
    volume: float = typer.Option(1.0, help="Audio volume level between 0.0 (mute) and 1.0 (max)."),
    loop: bool = typer.Option(False, help="Enable to play the video continuously in a loop."),
    charset: str = typer.Option(DEFAULT_ASCII_CHARS, help="String of characters to use for ASCII rendering."),
    disable_audio: bool = typer.Option(False, help="Disable audio playback entirely."),
):
    """
    Plays a video file in the terminal using ASCII characters.

    This tool converts video frames into text characters and displays them in your terminal window.
    It sync audio with FFmpeg. You can control size, speed, and volume via options.
    """
    global temporary_audio_path

    pygame.mixer.init(frequency=44100, size=-16, channels=2, buffer=512)
    pygame.mixer.music.set_volume(max(0.0, min(1.0, volume)))

    if not disable_audio:
        ffmpeg_exe = resolve_ffmpeg()
        temporary_audio_path = extract_audio(ffmpeg_exe, video, speed)
        pygame.mixer.music.load(temporary_audio_path)
        pygame.mixer.music.play()

    video_capture = cv2.VideoCapture(video)
    if not video_capture.isOpened():
        print("Error: Could not open video file.")
        raise typer.Exit(1)

    video_framerate = video_capture.get(cv2.CAP_PROP_FPS) or 24.0
    seconds_per_frame = (1.0 / video_framerate) / speed

    terminal_width, _ = shutil.get_terminal_size()
    ascii_width = max(10, int(terminal_width * scale))

    clear_screen()
    playback_start_time = time.perf_counter()
    current_frame_index = 0

    while not playback_stopped:
        read_successful, video_frame = video_capture.read()
        if not read_successful:
            if loop:
                video_capture.set(cv2.CAP_PROP_POS_FRAMES, 0)
                current_frame_index = 0
                if not disable_audio:
                    pygame.mixer.music.play()
                playback_start_time = time.perf_counter()
                continue
            break

        ascii_art_string = frame_to_ascii(video_frame, ascii_width, charset)
        move_cursor()
        sys.stdout.write(ascii_art_string)
        sys.stdout.flush()

        target_time = current_frame_index * seconds_per_frame
        elapsed_time = time.perf_counter() - playback_start_time
        sleep_duration = target_time - elapsed_time
        if sleep_duration > 0:
            time.sleep(sleep_duration)

        current_frame_index += 1

    video_capture.release()
    pygame.mixer.music.stop()
    pygame.mixer.quit()
    clear_screen()

    if temporary_audio_path and os.path.exists(temporary_audio_path):
        os.remove(temporary_audio_path)

if __name__ == "__main__":
    app()
